const RouteNames = {
  HOME: "/home",
  ABOUT_US: "/about-us",
  EVENTS: "/events",
  BLOGS_LIST: "/blogs-list",
  BLOGS_DETAIL: "/blogs-detail",
  APPLICATION: "/scholarship-program/:id/application",
  LOGIN: "/login",
  REGISTER: "/register",
  GOOGLE: "/login-google",
  NOT_FOUND: "/not-found",
  ACCOUNT_INFO: "/account-info",
  DASHBOARD: "/admin/dashboard",
  SCHOLARSHIP_PROGRAM: "/scholarship-program",
  SCHOLARSHIP_PROGRAM_DETAIL: "/scholarship-program/:id",
  ACTIVITY: "/activity",
  CHANGE_PASSWORD: "/change-password",
  MAJOR: "/major/:id",
  FORGOT_PASSWORD: "/forgot-password",
  CHAT: "/chat",
  CHAT_WITH_USER: "/chat/:id",
  INFORMATION: "/information",
  SKILLS: "/skills",
  FUNDER_APPLICATION: "/funder/application/:id",
  SERVICES: "/services",
  SERVICES_DETAIL: "/services/:id",
  REVIEWS: "/reviews",
  APPLICANT_REQUEST_INFORMATION: "provider/requestinformation/:id",
  PROVIDER_COMMENT_INFORMATION: "applicant/requestinformation/:id",
  APPLICANT_REQUEST_HISTORY: "/services-history",
  PROVIDER_INFORMATION: "/provider-information/:id",
  SERVICE_HISTORY_DETAILS: "/services-history/services/:id",
  REQUEST_HISTORY_DETAILS: "/services-history/request/:id",
  WALLET: "/wallet",
  CHOOSE_WINNER: "/funder/choose-winners/:id",
  PAYMENT_RESULT: "/payment/result",
  FORM_CREATE_SCHOLARSHIP_PROGRAM: "/create-scholarship-program",
  TEST: "/test",
  HISTORY: "/history",
  PROVIDER_LIST: "/provider-list",
  APPLICANT_PROFILE: "/applicant/profile",
  TRACKING_EXPERT: "/funder/tracking-expert",
  FUNDER_PROFILE: "/funder/profile",
  PROVIDER_PROFILE: "/provider/profile",
  APPLICATION_REVIEW: "/experts/application-review"
};

export default RouteNames;
