const RouteNames = {
    HOME: '/home',
    ABOUT_US: '/about-us',
    EVENTS: '/events',
    BLOGS_LIST: '/blogs-list',
    BLOGS_DETAIL: '/blogs-detail',
    APPLICATION: '/scholarship-program/:id/application',
    LOGIN: '/login',
    REGISTER: '/register',
    GOOGLE: '/login-google',
    NOT_FOUND: '/not-found',
    ACCOUNT_INFO: '/account-info',
    DASHBOARD: '/admin/dashboard',
    SCHOLARSHIP_PROGRAM:'/scholarship-program',
    SCHOLARSHIP_PROGRAM_DETAIL:'/scholarship-program/:id',
    ACTIVITY:'/activity',
    CHANGE_PASSWORD: '/change-password',
    MAJOR:'/major/:id',
    FORGOT_PASSWORD: '/forgot-password',
    CHAT: '/chat',
    INFORMATION: '/information',
    SKILLS: '/skills',
    FUNDER_APPLICATION: '/funder/application/:id',
    SERVICES: '/services',
    SERVICES_DETAIL: '/services/:id',
    REVIEWS: '/reviews',
    APPLICANT_REQUEST_INFORMATION: 'provider/requestinformation/:id',
    PROVIDER_COMMENT_INFORMATION: 'applicant/requestinformation/:id'
}

export default RouteNames
